Marge search text with master
Bnei-Baruch/kmedia-mdb pull request #618
Opened 2020-10-09 14:37 UTC by davgur

2020-10-13 01:59 UTC, YuriHechter requested changes
no scroll to the selected text from the generated link

2020-10-30 03:16 UTC, gshilin requested changes
Заодно измени в Transcription.js
if (relevantTextFiles.length == 0)
на ===

2020-10-30 03:16 UTC, gshilin commented on public/locales/en/common.json
> +    "text-copied-to-clipboard": "Text was copied!",
почему этого нет на остальных языках (cs, de)?

2020-10-30 03:16 UTC, gshilin commented on src/components/Pages/Unit/widgets/UnitMaterials/Materials.js
> +  const types = {};
верни форматирование

2020-10-30 03:39 UTC, merged