Selected series
Bnei-Baruch/kmedia-mdb pull request #704
Opened 2021-04-13 02:50 UTC by wissog

AR-754

2021-04-23 02:14 UTC, gshilin requested changes

2021-04-23 02:14 UTC, gshilin commented on public/locales/en/common.json
> +}
Return <new line> here please

2021-04-23 02:14 UTC, gshilin commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +    const key = id + '#' + level;
key = `${id}#${level}`

2021-04-23 02:14 UTC, gshilin commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +        <div key={node.id + '#' + initLevel}>
use ` please

2021-04-23 02:14 UTC, gshilin commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +        <Grid.Column key='bs#1' className="topics__section">
what do you need constant key for?

2021-04-23 02:14 UTC, gshilin commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +        <Grid.Column key='various#1' className="topics__section">
what do you need constant key for?

2021-04-23 02:14 UTC, gshilin commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +        <Grid.Column key='byTopics#1' className="topics__section">
what do you need constant key for?

2021-04-23 02:14 UTC, gshilin commented on src/components/Sections/Topics/TopicContainer.js
> +export default withNamespaces()(TopicContainer);
return new line

2021-04-23 02:14 UTC, gshilin commented on src/redux/modules/lessons.js
> +};
return it back

2021-04-23 02:20 UTC, wissog commented on public/locales/en/common.json
> +}
it's a json... what to return?

2021-04-23 02:22 UTC, wissog commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +        <Grid.Column key='bs#1' className="topics__section">
had errors on duplicate keys, so i made

2021-04-23 02:25 UTC, wissog commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +        <div key={node.id + '#' + initLevel}>
how it is better

2021-04-23 02:26 UTC, wissog commented on src/components/Sections/Lessons/tabs/Series/Container.js
> +        <Grid.Column key='various#1' className="topics__section">
duplicate key errors

2021-04-27 00:41 UTC, gshilin approved these changes

2021-04-27 00:42 UTC, merged