some-fixes
Bnei-Baruch/kmedia-mdb pull request #723
Opened 2021-05-31 03:03 UTC by wissog

converted classes to functions, deleted unused etc

2021-05-31 07:06 UTC, gshilin-sdb requested changes

2021-05-31 07:07 UTC, gshilin-sdb commented
Why are you removing `SameCollection` stuff?

2021-05-31 15:27 UTC, wissog commented
SameCollection is not in use, we made Recommended functionality instead
You still want to keep it?
בברכה,
גבריאל ויסוצקי
נייד: 054-5606-798


On Mon, 31 May 2021 at 10:07, Gregory Shilin ***@***.***>
wrote:

> Why are you removing SameCollection stuff?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Bnei-Baruch/kmedia-mdb/pull/723#issuecomment-851250796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHVVEUA7R2L5TPUP3P4UMLDTQMYU7ANCNFSM452ASKUA>
> .
>

2021-05-31 16:19 UTC, gshilin-sdb commented
No, I'm not.

2021-06-01 02:11 UTC, wissog commented on src/components/Filters/components/Date/YearMonthForm.js
> +        options={years.map(yea => ({ text: yea, value: yea }))}
ok

2021-06-22 00:07 UTC, gshilin approved these changes

2021-06-22 00:07 UTC, merged