Lint fixes
Bnei-Baruch/kmedia-mdb pull request #727
Opened 2021-06-25 02:41 UTC by wissog

files linting fixes - **apply after** the previous branch **eslint-files-fix**

2021-06-25 05:34 UTC, gshilin requested changes

2021-06-25 05:34 UTC, gshilin commented on src/components/AVPlayer/AVPlayer.js
> +        case 'play':
Все наши редакторы этого **не делают**. Пожалуйста, настрой lint

2021-06-25 06:25 UTC, wissog commented
Ты сначала первый branch возьми
Eslint-fixes
Там настройки

On Fri, Jun 25, 2021, 08:34 Gregory Shilin ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/AVPlayer/AVPlayer.js
> <https://github.com/Bnei-Baruch/kmedia-mdb/pull/727#discussion_r658486076>
> :
>
> > -        this.sendCallbackMessage(event.data, { status: 'ok', result: item });
>
> -        return;
>
> -      case 'isFullScreen':
>
> -        this.sendCallbackMessage(event.data, { status: 'ok', result: media.isFullScreen });
>
> -        return;
>
> -      case 'isLoading':
>
> -        this.sendCallbackMessage(event.data, { status: 'ok', result: media.isLoading });
>
> -        return;
>
> -      case 'isMuted':
>
> -        this.sendCallbackMessage(event.data, { status: 'ok', result: media.isMuted });
>
> -        return;
>
> -      case 'isPlaying':
>
> -        this.sendCallbackMessage(event.data, { status: 'ok', result: media.isPlaying });
>
> -        return;
>
> -      default:
>
> +        case 'play':
>
>
> Все наши редакторы этого *не делают*. Пожалуйста, настрой lint
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Bnei-Baruch/kmedia-mdb/pull/727#pullrequestreview-692462855>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHVVEUFHK6U6QEJAZMOUBGLTUQIPNANCNFSM47JAQKCA>
> .
>

2021-06-25 06:30 UTC, gshilin commented
Взял, делай rebase

2021-06-26 04:50 UTC, wissog commented
done
בברכה,
גבריאל ויסוצקי
נייד: 054-5606-798


On Fri, 25 Jun 2021 at 09:30, Gregory Shilin ***@***.***>
wrote:

> Взял, делай rebase
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Bnei-Baruch/kmedia-mdb/pull/727#issuecomment-868259269>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHVVEUGELJDGR4LXGYSEPSTTUQPB5ANCNFSM47JAQKCA>
> .
>

2021-06-29 00:43 UTC, merged